#!/usr/bin/bash
MAIN_FOLDER="$HOME/collinion"
PROGRAM_FOLDER="$MAIN_FOLDER/program"
ALGO_FILE="$PWD/$1"
FORMATED_ALGO="$PROGRAM_FOLDER/src/ALGO.c"
CELL_TYPE_FILE="$PROGRAM_FOLDER/include/cell_types.h"

# format the line starting by DEFINE_TYPE and put it in the file
if [[ -f ${ALGO_FILE} ]] ; then
	grep DEFINE_TYPE ${ALGO_FILE} | cut -d:  -f2-100 |  awk 'BEGIN {print "#include <collinion.h>\nenum cell_types {"} {print "\t",$0,","} END { print "NB_TYPES };" }' > ${CELL_TYPE_FILE}

	sed 's/.*DEFINE_TYPE.*//' ${ALGO_FILE} > ${FORMATED_ALGO}
else
	echo "[$0] .algo file not found"
	exit 1
fi

make -C ${PROGRAM_FOLDER} algo
mv "$PROGRAM_FOLDER/collinion" .
./collinion
exit 0
